### PR TITLE
Updated dependencies versions and fixed vulnerabilities

### PR DESCRIPTION
**Pull request by wmattei**
Updated all versions in package.json, upgrated compiler target to esnext, and solved dependencies vulnerabilities!

### CODE REVIEW

**Comment by fals** [comment]
I'm afraid that bumping the versions can break previous versions of angular. I will carefully check it, because if ti's the case I'll also bump our version to match angular major version. It'll be strange at first going from 1 to 8, but we can keep track of what works and not for some versions.

**Comment by wmattei** [comment]
Yeah ok, take your time, any problem you find you can tell me..

**Comment by fals** [comment]
HI! Can you merge development. I did some changes. As soon you fix it I will merge and deploy a new version with the tag v8.0.0 to match the new angular version

**Comment by wmattei** [comment]
@fals  Done!

**Review by fals — APPROVED** [review]
Merging it to master

**Pull request merged**
