### PR TITLE
Yarn support + extra unit test

### PR DESCRIPTION
**Pull request by mfdeveloper**
Fixes error when compile `@types` packages. Fixed versions on `package.json` and use [yarn](https://yarnpkg.com/pt-BR/) to create a **`yarn.lock`** file with exatly dependencies versions that your library works!

Added too:

-  A extra assertion to check if the pipe doesn't parses a formatted `CPF`.
- `.npmignore` file to avoid duplicated `.ts` with class/modules definitions. Without this, some test runners try to compile this and show errors. 
- Replace `gulp-clean` deprecated dependency to `del` package.

### CODE REVIEW

**Comment by mfdeveloper** [comment]
@fals This project is maintained yet?

**Comment by fals** [comment]
Yes, we're using It every day in our projects!😊

Em 29 de abr de 2017 6:41 PM, "Felipe Michel" <notifications@github.com>
escreveu:

**Comment by mfdeveloper** [comment]
Great!! @fals, Did you revise this PR? :sweat_smile:

**Review by fals — APPROVED** [review]
Thank you for your support! I'm merging your changes to master. Also I will publish the new version at npm, I saw that you already did the version increment!

**Pull request merged**
